# Generated by Django 4.1.5 on 2023-01-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='force',
            new_name='info',
        ),
    ]
